In [68]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf

In [69]:
df=pd.read_csv("Data/cleaned_data.csv")
df.head()

,id,name,image_url,is_closed,url,review_count,rating,transactions,price,group_city,cuisines,latitude,longitude,state
0,a0IET3_yCFcO36OqGSsisg,Eataly NYC Flatiron,https://s3-media4.fl.yelpcdn.com/bphoto/1UDlnu...,False,https://www.yelp.com/biz/eataly-nyc-flatiron-n...,6101,4.0,"delivery, pickup",2,New York City,Italian,40.742101,-73.989922,NY
1,zj8Lq1T8KIC5zwFief15jg,Prince Street Pizza,https://s3-media4.fl.yelpcdn.com/bphoto/PfI8oV...,False,https://www.yelp.com/biz/prince-street-pizza-n...,5028,4.5,"delivery, pickup",1,New York City,Italian,40.723088,-73.994530,NY
2,16ZnHpuaaBt92XWeJHCC5A,Olio e Più,https://s3-media4.fl.yelpcdn.com/bphoto/CUpPgz...,False,https://www.yelp.com/biz/olio-e-pi%C3%B9-new-y...,4828,4.5,"pickup, delivery",2,New York City,Italian,40.733798,-73.999774,NY
3,vyoA8dxwScuMV_AsTcjQcg,L & B Spumoni Gardens,https://s3-media1.fl.yelpcdn.com/bphoto/hN5xKw...,False,https://www.yelp.com/biz/l-and-b-spumoni-garde...,4648,4.0,"delivery, pickup",2,New York City,Italian,40.594715,-73.981316,NY
4,22nKUyCIbpnzR6R3_g1ptQ,Carmine's Italian Restaurant - Times Square,https://s3-media1.fl.yelpcdn.com/bphoto/0UszeE...,False,https://www.yelp.com/biz/carmines-italian-rest...,4640,4.0,"delivery, pickup",2,New York City,Italian,40.757498,-73.986653,NY

In [70]:
df['delivery'] = df['transactions'].str.contains('delivery', case=False, na=False)
df['pickup'] = df['transactions'].str.contains('pickup', case=False, na=False)
df['restaurant_reservation'] = df['transactions'].str.contains('restaurant_reservation', case=False, na=False)

# Fill NaN values with False in the new columns
df['delivery'] = df['delivery'].fillna(False)
df['pickup'] = df['pickup'].fillna(False)
df['restaurant_reservation'] = df['restaurant_reservation'].fillna(False)

In [71]:
y = df["price"]
X=df.drop(columns=['price', 'image_url', 'url', 'id', 'name', 'transactions'])



X= X.fillna(0)

In [72]:
X= pd.get_dummies(X).astype(int)
X

,is_closed,review_count,rating,latitude,longitude,delivery,pickup,restaurant_reservation,group_city_Albuquerque,group_city_Atlanta,...,state_ON,state_OR,state_PA,state_PE,state_SC,state_TN,state_TX,state_VA,state_WA,state_WI
0,0,6101,4,40,-73,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,5028,4,40,-73,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,4828,4,40,-73,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,4648,4,40,-73,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,4640,4,40,-73,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19140,0,8,3,35,-78,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19141,0,8,4,35,-78,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19142,0,8,5,35,-78,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19143,0,8,4,35,-78,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19144,0,8,4,35,-78,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.75, stratify=y)

In [86]:
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [87]:
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1= 10
hidden_nodes_layer2= 20
hidden_nodes_layer3= 10

nn = tf.keras.models.Sequential()

nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu')
)

#nn.add(
    #tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu')
#)

nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='relu')
)

nn.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid'))

nn.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_28 (Dense)            (None, 10)                910

 dense_29 (Dense)            (None, 10)                110

 dense_30 (Dense)            (None, 1)                 11

=================================================================
Total params: 1031 (4.03 KB)
Trainable params: 1031 (4.03 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [88]:
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [89]:
fit_model= nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
150/150 [==============================] - 1s 2ms/step - loss: -1.6255 - accuracy: 0.2936
Epoch 2/50
150/150 [==============================] - 0s 2ms/step - loss: -15.5041 - accuracy: 0.2984
Epoch 3/50
150/150 [==============================] - 0s 2ms/step - loss: -71.1282 - accuracy: 0.2984
Epoch 4/50
150/150 [==============================] - 0s 1ms/step - loss: -207.3573 - accuracy: 0.2984
Epoch 5/50
150/150 [==============================] - 0s 1ms/step - loss: -455.0091 - accuracy: 0.2984
Epoch 6/50
150/150 [==============================] - 0s 1ms/step - loss: -840.3071 - accuracy: 0.2984
Epoch 7/50
150/150 [==============================] - 0s 2ms/step - loss: -1381.6720 - accuracy: 0.2984
Epoch 8/50
150/150 [==============================] - 0s 2ms/step - loss: -2097.9309 - accuracy: 0.2984
Epoch 9/50
150/150 [==============================] - 0s 2ms/step - loss: -2999.1421 - accuracy: 0.2984
Epoch 10/50
150/150 [==============================] - 0s 3ms/step - loss: -4100.4917 - accuracy: 0.2984
Epoch 11/50
150/150 [==============================] - 0s 2ms/step - loss: -5417.5459 - accuracy: 0.2984
Epoch 12/50
150/150 [==============================] - 0s 2ms/step - loss: -6956.8555 - accuracy: 0.2984
Epoch 13/50
150/150 [==============================] - 0s 2ms/step - loss: -8734.9727 - accuracy: 0.2984
Epoch 14/50
150/150 [==============================] - 0s 2ms/step - loss: -10755.0713 - accuracy: 0.2984
Epoch 15/50
150/150 [==============================] - 0s 2ms/step - loss: -13024.8672 - accuracy: 0.2984
Epoch 16/50
150/150 [==============================] - 0s 2ms/step - loss: -15545.7217 - accuracy: 0.2984
Epoch 17/50
150/150 [==============================] - 0s 2ms/step - loss: -18328.7539 - accuracy: 0.2984
Epoch 18/50
150/150 [==============================] - 0s 3ms/step - loss: -21385.2949 - accuracy: 0.2984
Epoch 19/50
150/150 [==============================] - 0s 2ms/step - loss: -24723.0898 - accuracy: 0.2984
Epoch 20/50
150/150 [==============================] - 0s 2ms/step - loss: -28337.7578 - accuracy: 0.2984
Epoch 21/50
150/150 [==============================] - 0s 2ms/step - loss: -32239.3672 - accuracy: 0.2984
Epoch 22/50
150/150 [==============================] - 0s 2ms/step - loss: -36420.7969 - accuracy: 0.2984
Epoch 23/50
150/150 [==============================] - 0s 2ms/step - loss: -40901.8555 - accuracy: 0.2984
Epoch 24/50
150/150 [==============================] - 0s 3ms/step - loss: -45676.8945 - accuracy: 0.2984
Epoch 25/50
150/150 [==============================] - 0s 2ms/step - loss: -50751.2031 - accuracy: 0.2984
Epoch 26/50
150/150 [==============================] - 0s 2ms/step - loss: -56137.1484 - accuracy: 0.2984
Epoch 27/50
150/150 [==============================] - 0s 2ms/step - loss: -61830.1719 - accuracy: 0.2984
Epoch 28/50
150/150 [==============================] - 0s 2ms/step - loss: -67840.0234 - accuracy: 0.2984
Epoch 29/50
150/150 [==============================] - 0s 2ms/step - loss: -74159.2500 - accuracy: 0.2984
Epoch 30/50
150/150 [==============================] - 0s 2ms/step - loss: -80810.1797 - accuracy: 0.2984
Epoch 31/50
150/150 [==============================] - 0s 2ms/step - loss: -87802.3516 - accuracy: 0.2984
Epoch 32/50
150/150 [==============================] - 0s 2ms/step - loss: -95146.0391 - accuracy: 0.2984
Epoch 33/50
150/150 [==============================] - 0s 2ms/step - loss: -102852.7109 - accuracy: 0.2984
Epoch 34/50
150/150 [==============================] - 0s 2ms/step - loss: -110880.6562 - accuracy: 0.2984
Epoch 35/50
150/150 [==============================] - 0s 2ms/step - loss: -119250.7891 - accuracy: 0.2984
Epoch 36/50
150/150 [==============================] - 0s 2ms/step - loss: -128002.1797 - accuracy: 0.2984
Epoch 37/50
150/150 [==============================] - 0s 2ms/step - loss: -137112.1094 - accuracy: 0.2984
Epoch 38/50
150/150 [==============================] - 0s 2ms/step - loss: -146579.0781 - accuracy: 0.2984
Epoch 39/50
150/150 [==============================] - 0s 2ms/step - loss: -156406.1094 - accuracy: 0.2984
Epoch 40/50
150/150 [==============================] - 0s 2ms/step - loss: -166624.6406 - accuracy: 0.2984
Epoch 41/50
150/150 [==============================] - 0s 2ms/step - loss: -177224.7500 - accuracy: 0.2984
Epoch 42/50
150/150 [==============================] - 0s 2ms/step - loss: -188182.6562 - accuracy: 0.2984
Epoch 43/50
150/150 [==============================] - 0s 2ms/step - loss: -199553.4219 - accuracy: 0.2984
Epoch 44/50
150/150 [==============================] - 0s 3ms/step - loss: -211347.3906 - accuracy: 0.2984
Epoch 45/50
150/150 [==============================] - 0s 2ms/step - loss: -223531.4375 - accuracy: 0.2984
Epoch 46/50
150/150 [==============================] - 0s 2ms/step - loss: -236117.4688 - accuracy: 0.2984
Epoch 47/50
150/150 [==============================] - 0s 2ms/step - loss: -249116.5156 - accuracy: 0.2984
Epoch 48/50
150/150 [==============================] - 0s 3ms/step - loss: -262523.4375 - accuracy: 0.2984
Epoch 49/50
150/150 [==============================] - 0s 2ms/step - loss: -276401.0625 - accuracy: 0.2984
Epoch 50/50
150/150 [==============================] - 0s 2ms/step - loss: -290687.8750 - accuracy: 0.2984

In [83]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

419/419 - 1s - loss: -4.7368e+05 - accuracy: 0.3189 - 525ms/epoch - 1ms/step
Loss: -473682.9375, Accuracy: 0.31890761852264404

In [84]:
nn.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_25 (Dense)            (None, 10)                910

 dense_26 (Dense)            (None, 10)                110

 dense_27 (Dense)            (None, 1)                 11

=================================================================
Total params: 1031 (4.03 KB)
Trainable params: 1031 (4.03 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________